### ISSUE TITLE
`tellStopped` method parameters type definition is wrong

### ISSUE THREAD

**Issue by nepsyn** [importantimport/a2#1]
`Aria2.tellStopped` method type definition is different from aria2c's official document.

In code file [a2/c/src/methods.ts](https://github.com/importantimport/a2/blob/3209922137df23579cf478be4862b2d0942ca03c/c/src/methods.ts#LL93C63-L93C63) line 93:

```typescript
  declare tellStopped: (keys?: string[]) => TellStatusResult[]
```

This is the definition in [aria2c official document](https://aria2.github.io/manual/en/html/aria2c.html#aria2.tellStopped):

![image](https://github.com/importantimport/a2/assets/28952870/ac1a1e7d-2369-4c8d-8084-962c0b61ccde)

**Comment by kwaa** [comment]
Fixed in [`0.1.1`](https://www.npmjs.com/package/a2c/v/0.1.1)
